import { useState, useEffect } from "react";
import { generateRoadmap } from "@/api";
import { CheckCircle2, Circle, Clock, Info, Loader2, MapPin, Zap, ShieldAlert, Rocket } from "lucide-react";
import { Button } from "../ui/button";
import { toast } from "sonner";
import { motion } from "framer-motion";

interface RoadmapStep {
  id: number;
  title: string;
  description: string;
  type: "core" | "prerequisite";
  estimated_time: string;
}

interface Roadmap {
  title: string;
  pacing: string;
  steps: RoadmapStep[];
}

interface RoadmapTabProps {
  initialData?: Roadmap;
  onNavigateToMultimedia?: () => void;
}

export default function RoadmapTab({ initialData, onNavigateToMultimedia }: RoadmapTabProps) {
  const [roadmap, setRoadmap] = useState<Roadmap | null>(initialData || null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRoadmap = async () => {
    if (initialData) return;
    
    // Check if a roadmap was just generated by the quiz
    const lastRoadmap = localStorage.getItem("last_roadmap");
    if (lastRoadmap) {
        try {
            setRoadmap(JSON.parse(lastRoadmap));
            localStorage.removeItem("last_roadmap"); // Clear it so it doesn't persist forever
            return;
        } catch (e) {
            console.error("Failed to parse last roadmap", e);
        }
    }

    const evalId = localStorage.getItem("last_eval_id");
    if (!evalId) {
      setError("Please complete a quiz diagnostic first to generate your personalized roadmap.");
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const storedEval = localStorage.getItem("last_eval_data");
      if (!storedEval) {
        throw new Error("No diagnostic data found. Please complete the quiz first.");
      }
      
      const { summary, scores, gaps, topic: evalTopic } = JSON.parse(storedEval);
      const data = await generateRoadmap(summary, scores, gaps, evalTopic);
      
      if (data.error) throw new Error(data.error);
      setRoadmap(data);
      toast.success("Personalized roadmap generated!");
    } catch (err) {
      setError("Failed to generate roadmap. Please try again.");
      toast.error("Roadmap generation failed");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRoadmap();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-24 space-y-6">
        <div className="relative">
          <div className="h-24 w-24 rounded-full border-4 border-primary/20 border-t-primary animate-spin" />
          <MapPin className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-8 w-8 text-primary animate-pulse" />
        </div>
        <div className="text-center space-y-2">
          <h3 className="text-2xl font-bold text-foreground">Mapping Your Learning Journey</h3>
          <p className="text-muted-foreground animate-pulse">Analyzing diagnostic gaps and injecting prerequisites...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="glass-card p-12 text-center space-y-6 animate-fade-in max-w-2xl mx-auto">
        <div className="h-20 w-20 bg-destructive/10 rounded-full flex items-center justify-center mx-auto">
          <ShieldAlert className="h-10 w-10 text-destructive" />
        </div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold text-foreground">Diagnostic Required</h2>
          <p className="text-muted-foreground">{error}</p>
        </div>
        <Button variant="gradient" size="lg" onClick={() => document.getElementById("tab-quiz")?.click()}>
          Go to Quiz Diagnostic 🧠
        </Button>
      </div>
    );
  }

  if (!roadmap || !roadmap.steps) {
    return (
      <div className="flex flex-col items-center justify-center py-24 space-y-6">
        <div className="h-12 w-12 rounded-full border-4 border-primary/20 border-t-primary animate-spin" />
        <p className="text-muted-foreground">Preparing your mastery path...</p>
      </div>
    );
  }

  return (
    <div className="space-y-10 animate-fade-in max-w-4xl mx-auto pb-20">
      <div className="text-center space-y-4">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-black uppercase tracking-widest">
          <Zap className="h-3.5 w-3.5" /> {roadmap.pacing}
        </div>
        <h2 className="text-4xl md:text-5xl font-black text-foreground tracking-tight">
          {roadmap.title}
        </h2>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Based on your diagnostic performance, we've crafted this step-by-step path to mastery.
        </p>
      </div>

      <div className="relative space-y-0">
        {/* The Path Line */}
        <div className="absolute left-[27px] md:left-1/2 top-10 bottom-10 w-1 bg-gradient-to-b from-primary via-purple-500 to-blue-500 rounded-full opacity-20 hidden md:block" />
        <div className="absolute left-[27px] top-10 bottom-10 w-1 bg-gradient-to-b from-primary via-purple-500 to-blue-500 rounded-full opacity-20 md:hidden" />

        {roadmap.steps.map((step, idx) => {
          const isLeft = idx % 2 === 0;
          const isPrereq = step.type === "prerequisite";

          return (
            <motion.div
              key={step.id}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              viewport={{ once: true }}
              className={`relative flex items-center justify-between mb-12 md:mb-20 w-full ${
                isLeft ? "md:flex-row-reverse" : "md:flex-row"
              }`}
            >
              {/* Content Card */}
              <div className="w-full md:w-[42%] ml-14 md:ml-0">
                <div className={`glass-card p-6 md:p-8 hover:scale-[1.02] transition-all duration-300 shadow-xl relative group ${
                  isPrereq ? "border-l-4 border-l-amber-500 bg-amber-500/5" : "border-l-4 border-l-primary"
                }`}>
                  {isPrereq && (
                    <div className="absolute -top-3 right-4 px-3 py-1 bg-amber-500 text-white text-[10px] font-black rounded-full shadow-lg">
                      PREREQUISITE
                    </div>
                  )}
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-[10px] font-black text-primary uppercase tracking-widest">STEP {idx + 1}</span>
                    <div className="flex items-center gap-1.5 text-muted-foreground text-xs font-bold">
                       <Clock className="h-3.5 w-3.5" /> {step.estimated_time}
                    </div>
                  </div>
                  <h4 className="text-xl md:text-2xl font-bold text-foreground mb-3 group-hover:text-primary transition-colors">
                    {step.title}
                  </h4>
                  <p className="text-muted-foreground leading-relaxed text-sm md:text-base">
                    {step.description}
                  </p>
                  
                  <div className="mt-6 flex justify-end">
                     <Button 
                        variant="ghost" 
                        size="sm" 
                        className="rounded-xl font-bold text-xs group"
                        onClick={onNavigateToMultimedia}
                     >
                        Start Learning <Rocket className="ml-2 h-3.5 w-3.5 group-hover:translate-x-1 transition-transform" />
                     </Button>
                  </div>
                </div>
              </div>

              {/* Marker */}
              <div className="absolute left-0 md:left-1/2 md:-translate-x-1/2 flex h-14 w-14 items-center justify-center rounded-full bg-background border-4 border-muted shadow-2xl z-10">
                {isPrereq ? (
                   <div className="h-10 w-10 rounded-full bg-amber-500 flex items-center justify-center text-white shadow-lg shadow-amber-500/30">
                      <ShieldAlert className="h-5 w-5" />
                   </div>
                ) : (
                   <div className="h-10 w-10 rounded-full bg-primary flex items-center justify-center text-white shadow-lg shadow-primary/30">
                      <CheckCircle2 className="h-5 w-5" />
                   </div>
                )}
              </div>

              {/* Space Filler for MD+ screens */}
              <div className="hidden md:block w-[42%]" />
            </motion.div>
          );
        })}
      </div>

      <div className="glass-card p-8 text-center bg-gradient-to-r from-primary/10 to-purple-500/10 border-none">
         <h4 className="text-xl font-bold mb-2">Roadmap Generated Successfully!</h4>
         <p className="text-muted-foreground mb-6">This path is uniquely tailored to your diagnostic results for '{roadmap.title}'.</p>
         <Button variant="outline" onClick={fetchRoadmap} className="rounded-xl">
            Refresh Roadmap 🔄
         </Button>
      </div>
    </div>
  );
}
