import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Share2, Link as LinkIcon, Download, Check, Copy, Loader2, FileText, Globe, Sparkles } from "lucide-react";
import { createShare } from "@/api";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  sessionTitle: string;
  sessionData: any;
  mindMapImage?: string | null;
}

export default function ShareModal({ isOpen, onClose, sessionTitle, sessionData, mindMapImage }: ShareModalProps) {
  const [loadingLink, setLoadingLink] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);

  const handleGenerateLink = async () => {
    setLoadingLink(true);
    try {
      const res = await createShare(sessionTitle, sessionData);
      setShareUrl(res.share_url);
      toast.success("Share link generated!");
    } catch (e) {
      toast.error("Failed to generate link");
    } finally {
      setLoadingLink(false);
    }
  };

  const copyToClipboard = () => {
    if (!shareUrl) return;
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    toast.success("Link copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = async () => {
    setExportingPdf(true);
    try {
      const doc = new jsPDF("p", "mm", "a4");
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const contentWidth = pageWidth - (margin * 2);
      let y = margin;

      // --- Helper Functions ---
      const addText = (text: string, size: number, style: "normal" | "bold" = "normal", color: [number, number, number] = [0, 0, 0]) => {
        doc.setFontSize(size);
        doc.setFont("helvetica", style);
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(text, contentWidth);
        
        if (y + (lines.length * (size/2)) > 280) {
          doc.addPage();
          y = margin;
          addHeader();
        }
        
        doc.text(lines, margin, y);
        y += (lines.length * (size/2)) + 2;
      };

      const addHeader = () => {
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by AutoLearn AI Studio", margin, 10);
        doc.text(new Date().toLocaleDateString(), pageWidth - margin - 20, 10);
        doc.setDrawColor(230, 230, 230);
        doc.line(margin, 12, pageWidth - margin, 12);
      };

      // --- Initial Page ---
      addHeader();
      
      // Title Section
      y += 10;
      doc.setFontSize(26);
      doc.setTextColor(124, 58, 237); // Primary Purple
      doc.setFont("helvetica", "bold");
      doc.text(sessionTitle, margin, y);
      y += 15;

      // 1. Notes Section
      const notes = sessionData?.notes || [];
      if (notes.length > 0) {
        y += 5;
        addText("STUDY NOTES", 14, "bold", [30, 41, 59]);
        doc.setDrawColor(124, 58, 237);
        doc.line(margin, y - 1, margin + 30, y - 1);
        y += 8;

        notes.forEach((note: any) => {
          addText(note.title, 12, "bold", [15, 23, 42]);
          y += 1;
          const bulletPoints = note.content.split("\n").filter((p: string) => p.trim());
          bulletPoints.forEach((point: string) => {
            const cleanPoint = point.replace(/^[•\-\*]\s*/, "");
            addText(`• ${cleanPoint}`, 10, "normal", [71, 85, 105]);
          });
          y += 6;
        });
      }

      // 2. Quiz Section
      const quiz = sessionData?.quiz || [];
      if (quiz.length > 0) {
        if (y > 40) { doc.addPage(); y = margin; addHeader(); }
        y += 10;
        addText("QUIZ & PRACTICE", 14, "bold", [30, 41, 59]);
        y += 8;

        quiz.forEach((q: any, i: number) => {
          addText(`${i + 1}. ${q.question}`, 11, "bold", [15, 23, 42]);
          y += 2;
          q.options.forEach((opt: string, optIdx: number) => {
            const isCorrect = optIdx === q.correct;
            const color: [number, number, number] = isCorrect ? [22, 163, 74] : [71, 85, 105];
            const prefix = isCorrect ? "[CORRECT] " : "  - ";
            addText(`${prefix}${opt}`, 10, "normal", color);
          });
          y += 5;
        });
      }

      // 3. Mind Map Section
      if (mindMapImage) {
        doc.addPage();
        y = margin;
        addHeader();
        y += 10;
        addText("MIND MAP OVERVIEW", 14, "bold", [124, 58, 237]);
        y += 5;
        
        const imgWidth = contentWidth;
        const imgHeight = (imgWidth * 9) / 16; // 16:9 aspect ratio
        doc.addImage(mindMapImage, "PNG", margin, y, imgWidth, imgHeight);
        y += imgHeight + 10;
      }

      // 4. Flashcards Section
      const flashcards = sessionData?.flashcards || [];
      if (flashcards.length > 0) {
        if (y > 40) { doc.addPage(); y = margin; addHeader(); }
        y += 10;
        addText("FLASHCARDS (Q&A)", 14, "bold", [30, 41, 59]);
        y += 8;

        flashcards.forEach((card: any) => {
          const question = card.front || card.question || card.q || "N/A";
          const answer = card.back || card.answer || card.a || "N/A";
          addText(`Q: ${question}`, 11, "bold", [124, 58, 237]);
          addText(`A: ${answer}`, 10, "normal", [71, 85, 105]);
          y += 4;
        });
      }

      doc.save(`${sessionTitle.replace(/\s+/g, "_")}_Learning_Suite.pdf`);
      toast.success("Premium PDF Exported!");
    } catch (e) {
      console.error(e);
      toast.error("Failed to generate PDF");
    } finally {
      setExportingPdf(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-lg bg-slate-900 border border-white/10 text-white rounded-[2rem] shadow-2xl backdrop-blur-2xl overflow-hidden p-0">
        {/* Header Aesthetic Area */}
        <div className="bg-gradient-to-br from-primary/20 to-purple-500/10 p-8 border-b border-white/5">
          <DialogHeader className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="h-12 w-12 rounded-2xl bg-primary flex items-center justify-center text-white shadow-lg shadow-primary/30">
                <Share2 className="h-6 w-6" />
              </div>
              <div>
                <DialogTitle className="text-2xl font-black tracking-tight">Share Studio</DialogTitle>
                <DialogDescription className="text-slate-300 font-medium">
                  Present your findings or collaborate with others.
                </DialogDescription>
              </div>
            </div>
          </DialogHeader>
        </div>

        <div className="p-8 space-y-8">
          {/* Share Link Section */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-primary">
              <LinkIcon className="h-4 w-4" />
              <h4 className="text-sm font-black uppercase tracking-[0.15em]">Shareable Link</h4>
            </div>
            
            {shareUrl ? (
              <div className="flex flex-col gap-3 animate-in fade-in slide-in-from-bottom-2 duration-500">
                <div className="group relative flex items-center bg-slate-950 border border-white/10 rounded-2xl p-4 transition-all hover:border-primary/50">
                  <input 
                    readOnly 
                    value={shareUrl} 
                    className="flex-1 bg-transparent border-none outline-none text-sm text-slate-200 font-medium pr-4"
                  />
                  <Button 
                    onClick={copyToClipboard} 
                    size="sm" 
                    className={`rounded-xl px-4 font-bold transition-all ${copied ? "bg-green-600 hover:bg-green-600" : "bg-primary hover:bg-primary/90"}`}
                  >
                    {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                    {copied ? "Copied!" : "Copy Link"}
                  </Button>
                </div>
                <p className="text-[10px] text-center text-slate-500 font-bold uppercase tracking-widest flex items-center justify-center gap-2">
                  <Globe className="h-3 w-3" /> Publicly accessible to anyone with the link
                </p>
              </div>
            ) : (
              <Button 
                onClick={handleGenerateLink} 
                disabled={loadingLink}
                className="w-full rounded-2xl h-14 gap-3 font-black text-lg bg-white text-black hover:bg-slate-200 transition-all active:scale-95 shadow-xl"
              >
                {loadingLink ? <Loader2 className="h-6 w-6 animate-spin" /> : <Sparkles className="h-6 w-6" />}
                Generate Smart Link
              </Button>
            )}
          </div>

          <div className="flex items-center gap-4">
            <div className="h-px flex-1 bg-white/5"></div>
            <span className="text-[10px] font-black text-slate-500 tracking-widest">OR</span>
            <div className="h-px flex-1 bg-white/5"></div>
          </div>

          {/* PDF Export Section */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-emerald-400">
              <FileText className="h-4 w-4" />
              <h4 className="text-sm font-black uppercase tracking-[0.15em]">Professional Export</h4>
            </div>
            
            <Button 
              onClick={handleDownloadPdf}
              disabled={exportingPdf}
              variant="outline"
              className="w-full rounded-2xl h-14 gap-3 font-black text-lg border-white/10 bg-white/5 hover:bg-white/10 transition-all hover:border-emerald-500/50"
            >
              {exportingPdf ? <Loader2 className="h-6 w-6 animate-spin" /> : <Download className="h-6 w-6" />}
              Export PDF Document
            </Button>
            <p className="text-[10px] text-center text-slate-500 font-bold uppercase tracking-widest">
              Includes formatted notes, quizzes, and flashcards
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
