import { Button } from "@/components/ui/button";
import { Upload, BookOpen, Sparkles, Brain, Zap, Target } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useStudy } from "@/context/StudyContext";

export default function DashboardPage() {
  const navigate = useNavigate();
  const { sessions, user, quizStats } = useStudy();

  const quizAccuracy = quizStats.totalQuestions > 0
    ? `${Math.round((quizStats.totalCorrect / quizStats.totalQuestions) * 100)}%`
    : "0%";

  const stats = [
    { label: "Lessons Completed", value: sessions.length.toString(), icon: BookOpen, color: "text-primary" },
    { label: "Quiz Accuracy", value: quizAccuracy, icon: Target, color: "text-secondary" },
    // { label: "Study Streak", value: sessions.length > 0 ? "1 day" : "0 days", icon: Zap, color: "text-amber-500" },
    { label: "AI Insights", value: (sessions.length * 42).toString(), icon: Brain, color: "text-primary" },
  ];

  const recentSessions = sessions.slice(0, 3);

  return (
    <div className="p-6 md:p-8 max-w-6xl mx-auto space-y-8">
      {/* Hero Section */}
      <section className="gradient-bg rounded-3xl p-8 md:p-12 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-72 h-72 bg-primary/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
        <div className="absolute bottom-0 left-0 w-48 h-48 bg-secondary/10 rounded-full blur-3xl translate-y-1/2 -translate-x-1/2" />

        <div className="relative z-10 max-w-2xl">
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="h-5 w-5 text-primary animate-pulse" />
            <span className="text-sm font-medium text-primary">AI-Powered Learning Studio</span>
          </div>
          <h1 className="font-heading text-4xl md:text-5xl font-bold text-foreground mb-4 animate-slide-up">
            Welcome back, <span className="gradient-text text-primary">{user || "Scholar"}</span>
          </h1>
          <p className="text-lg text-muted-foreground mb-8 animate-slide-up stagger-1" style={{ opacity: 0 }}>
            Upload any content and get personalized learning instantly. Notes, quizzes, flashcards — all generated by AI.
          </p>
          <div className="flex flex-wrap gap-4 animate-slide-up stagger-2" style={{ opacity: 0 }}>
            <Button variant="gradient" size="xl" onClick={() => navigate("/upload")} className="animate-pulse-glow">
              <Upload className="h-5 w-5" />
              Upload File
            </Button>
            <Button variant="glass" size="xl" onClick={() => navigate("/learning")}>
              <BookOpen className="h-5 w-5" />
              Start Learning
            </Button>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {stats.map((stat, i) => (
          <div key={stat.label} className="glass-card-hover p-5 text-center animate-slide-up" style={{ opacity: 0, animationDelay: `${0.1 * (i + 1)}s` }}>
            <stat.icon className={`h-6 w-6 mx-auto mb-2 ${stat.color}`} />
            <p className="text-2xl font-bold font-heading text-foreground">{stat.value}</p>
            <p className="text-xs text-muted-foreground mt-1">{stat.label}</p>
          </div>
        ))}
      </section>

      {/* Recent Activity */}
      <section>
        <h2 className="font-heading text-xl font-semibold text-foreground mb-4">Recent Activity</h2>
        {sessions.length === 0 ? (
          <div className="glass-card p-12 text-center border-dashed border-2">
            <p className="text-muted-foreground font-medium">No learning materials yet. Start by uploading a file!</p>
          </div>
        ) : (
          <div className="grid md:grid-cols-3 gap-4">
            {recentSessions.map((item, i) => (
              <div
                key={item.id}
                className="glass-card-hover p-5 cursor-pointer animate-slide-up"
                style={{ opacity: 0, animationDelay: `${0.1 * (i + 1)}s` }}
                onClick={() => {
                  // If we click it, set it as current and go to learning
                  navigate("/learning");
                }}
              >
                <div className="flex items-center gap-3 mb-3">
                  <span className="text-2xl">{item.type === "File Upload" ? "📄" : "✍️"}</span>
                  <div>
                    <p className="font-medium text-foreground text-sm truncate max-w-[150px]">{item.title}</p>
                    <p className="text-[10px] text-muted-foreground uppercase font-bold tracking-tighter">{item.type}</p>
                  </div>
                </div>
                <div className="w-full bg-muted rounded-full h-2">
                  <div className="bg-primary rounded-full h-2 transition-all duration-700" style={{ width: `100%` }} />
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">Generated {item.timestamp.split(' ')[0]}</p>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
